/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    AppLogos: typeof import('./src/components/AppLogos.vue')['default']
    CustomTabBar: typeof import('./src/components/CustomTabBar.vue')['default']
    EmoteImage: typeof import('./src/components/EmoteImage.vue')['default']
    InputEntry: typeof import('./src/components/InputEntry.vue')['default']
    LiveBadge: typeof import('./src/components/photo/LiveBadge.vue')['default']
    LivePhoto: typeof import('./src/components/photo/livePhoto.vue')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
    PhotoShareGenerator: typeof import('./src/components/photo/PhotoShareGenerator.vue')['default']
    PhotoViewer: typeof import('./src/components/photo/photoViewer.vue')['default']
    ThemeToggle: typeof import('./src/components/ThemeToggle.vue')['default']
  }
}
