import { presetUni } from '@uni-helper/unocss-preset-uni'

import { presetAno } from 'ano-ui'
import {
  defineConfig,
  presetIcons,
  transformerDirectives,
  transformerVariantGroup,
} from 'unocss'

export default defineConfig({
  presets: [
    presetUni(),
    presetAno(),
    presetIcons({
      scale: 1.2,
      warn: true,
      extraProperties: {
        'display': 'inline-block',
        'vertical-align': 'middle',
      },
    }),
  ],
  transformers: [
    transformerDirectives(),
    transformerVariantGroup(),
  ],
  rules: [
    ['text-[#1a1a2e]', { color: '#1a1a2e' }],
    ['text-[#64748b]', { color: '#64748b' }],
    ['text-[#94a3b8]', { color: '#94a3b8' }],
    ['text-[#6366f1]', { color: '#6366f1' }],
    ['tracking-[0.05em]', { 'letter-spacing': '0.05em' }],
    ['tracking-[0.02em]', { 'letter-spacing': '0.02em' }],
    ['tracking-[0.03em]', { 'letter-spacing': '0.03em' }],
    ['border-[rgba(99,102,241,0.4)]', { 'border-color': 'rgba(99, 102, 241, 0.4)' }],
    ['border-[rgba(139,92,246,0.3)]', { 'border-color': 'rgba(139, 92, 246, 0.3)' }],
    ['border-[rgba(99,102,241,0.08)]', { 'border-color': 'rgba(99, 102, 241, 0.08)' }],
    ['border-[rgba(99,102,241,0.1)]', { 'border-color': 'rgba(99, 102, 241, 0.1)' }],
    ['bg-[rgba(99,102,241,0.1)]', { 'background-color': 'rgba(99, 102, 241, 0.1)' }],
  ],
  theme: {
    colors: {
      primary: {
        DEFAULT: '#6366f1',
        hover: '#4f46e5',
        light: '#a5b4fc',
        dark: '#4338ca',
      },
      secondary: {
        DEFAULT: '#8b5cf6',
        hover: '#7c3aed',
        light: '#c4b5fd',
      },
      accent: {
        DEFAULT: '#06b6d4',
        light: '#22d3ee',
      },
      success: {
        DEFAULT: '#10b981',
        light: '#34d399',
      },
      warning: {
        DEFAULT: '#f59e0b',
        light: '#fbbf24',
      },
      error: {
        DEFAULT: '#ef4444',
        light: '#f87171',
      },
      bg: {
        primary: 'var(--bg-primary)',
        secondary: 'var(--bg-secondary)',
        tertiary: 'var(--bg-tertiary)',
        card: 'var(--bg-card)',
        elevated: 'var(--bg-elevated)',
      },
      text: {
        primary: 'var(--text-primary)',
        secondary: 'var(--text-secondary)',
        tertiary: 'var(--text-tertiary)',
        muted: 'var(--text-muted)',
        inverse: 'var(--text-inverse)',
      },
      border: {
        DEFAULT: 'var(--border-color)',
        light: 'var(--border-light)',
        dark: 'var(--border-dark)',
      },
    },
    fontSize: {
      'xs': '12px',
      'sm': '14px',
      'base': '16px',
      'lg': '18px',
      'xl': '20px',
      '2xl': '24px',
      '3xl': '30px',
      '4xl': '36px',
      '5xl': '48px',
    },
    borderRadius: {
      'none': '0',
      'sm': '4px',
      'DEFAULT': '8px',
      'md': '12px',
      'lg': '16px',
      'xl': '20px',
      '2xl': '24px',
      '3xl': '32px',
      'full': '9999px',
    },
    boxShadow: {
      'sm': '0 1px 2px 0 rgb(0 0 0 / 0.05)',
      'DEFAULT': '0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1)',
      'md': '0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)',
      'lg': '0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)',
      'xl': '0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1)',
      '2xl': '0 25px 50px -12px rgb(0 0 0 / 0.25)',
    },
  },
  shortcuts: {
    'bg-theme': 'bg-bg-primary',
    'bg-theme-secondary': 'bg-bg-secondary',
    'bg-theme-card': 'bg-bg-card',
    'text-theme': 'text-text-primary',
    'text-theme-secondary': 'text-text-secondary',
    'text-theme-tertiary': 'text-text-tertiary',
    'text-theme-muted': 'text-text-muted',
    'border-theme': 'border-border',
    'card': 'bg-bg-card rounded-xl border border-border p-4',
    'card-elevated': 'bg-bg-elevated rounded-xl shadow-lg p-4',
    'btn': 'px-4 py-2 rounded-lg font-medium transition-all duration-300 active:scale-95',
    'btn-primary': 'btn bg-primary text-white hover:bg-primary-hover',
    'btn-secondary': 'btn bg-secondary text-white hover:bg-secondary-hover',
    'btn-outline': 'btn border border-border bg-transparent hover:bg-bg-secondary',
    'btn-ghost': 'btn bg-transparent hover:bg-bg-secondary',
    'input-base': 'w-full px-4 py-3 rounded-lg border border-border bg-bg-card text-text-primary placeholder:text-text-muted focus:border-primary focus:ring-1 focus:ring-primary transition-all',
    'flex-center': 'flex items-center justify-center',
    'flex-between': 'flex items-center justify-between',
    'flex-col-center': 'flex flex-col items-center justify-center',
    'text-dark': 'text-[#1a1a2e]',
    'text-gray': 'text-[#64748b]',
    'text-light': 'text-[#94a3b8]',
    'text-primary-color': 'text-[#6366f1]',
    'tracking-wide': 'tracking-[0.05em]',
    'tracking-normal': 'tracking-[0.02em]',
    'tracking-tight': 'tracking-[0.03em]',
    'border-primary-light': 'border-[rgba(99,102,241,0.6)]',
    'border-secondary-light': 'border-[rgba(139,92,246,0.5)]',
    'border-primary-ultra-light': 'border-[rgba(99,102,241,0.08)]',
    'border-primary-super-light': 'border-[rgba(99,102,241,0.1)]',
    'bg-primary-ultra-light': 'bg-[rgba(99,102,241,0.1)]',
    'bg-white-80': 'bg-white/80',
    'bg-white-60': 'bg-white/60',
  },
})
